Fix/fiducial rng
pyGSTio/pyGSTi pull request #254
Opened 2022-08-09 23:25 UTC by johnkgamble

The GRASP implementation of fiducial generation was ignoring the `seed` kwarg passed to the solver. This PR addresses the issue by instancing a random number generator with a given seed in GRASP-based fiducial generation. This rng is then passed around as needed by GRASP. 

Note: many of the changes here are just black auto-formatting. The substantive changes are quite minimal.

2022-08-11 14:25 UTC, enielse requested changes
Technically this PR seems fine, and adds plumbing to send a random number generator down into the GRASP algorithm internals so that the randomness can be replicated deterministically using a (pseudorandom) number generator.  However, most of the ~650 changes are just stylistic (e.g. whitespace conventions, single vs double quotes, etc.) and don't change functionality at all.  (Maybe an editing tool was used that does this automatically according to its own Python style preferences?)  Before accepting this PR, lets clean this up so that only the substantive changes are made, as this makes tracking changes much easier and cleaner.  I've gone through and marked what I think are all the substantive changes in my review comments.  Assuming these are correct, I'm happy to create a separate PR that just updates these parts.

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/fiducialselection.py
> +    rng = random.Random(seed)
Marking this as a substantial (non-style) change

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/fiducialselection.py
> +                    rng=rng,
Marked as a substantial change.

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/grasp.py
> +    rng=None,
Marked as substantial change - adds rng arg to signature, docstring, and within function body below.

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/grasp.py
> +        chosenIdx = rng.choice(rclIdxs)
This is a substantial change, in particular

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/grasp.py
> +    rng=None,
Here's another substantial change - adding `rng` argument again in place of the `seed` argument.

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/grasp.py
> +    rng = random.Random(seed)
Marked as substantial change

2022-08-11 14:25 UTC, enielse commented on pygsti/algorithms/grasp.py
> +            rng=rng,
Marked as substantial change

2022-08-11 15:23 UTC, johnkgamble commented
@enielse - correct you are, sorry! Most of the changes are due to [black](https://black.readthedocs.io/en/stable/). I'll push up a minimal version later today. 

Black is extremely useful overall and used by tons of projects; I'm going to open an issue ticket to discuss the prospect of running all of pygsti through it to make everything easier.

2022-08-11 15:30 UTC, enielse commented
Ah, right - this was mentioned in the original PR but I didn't realize "black" was an editor :).  Yes, we'd be open to bulk reformatting but I think it's wise to keep that separated from functional changes to keep the history more readable.  Starting a separate discussion in an issue seems like a great plan.

2022-08-11 23:39 UTC, johnkgamble commented
@enielse , I've made just the minimal changes now - can you take another look? Thanks!

2022-08-12 11:18 UTC, enielse approved these changes
Looks great!

2022-08-12 11:19 UTC, merged