WIP: leakage-aware gauge optimization
pyGSTio/pyGSTi pull request #410
Opened 2024-03-19 19:15 UTC by rileyjmurray

2024-03-19 20:00 UTC, rileyjmurray commented on pygsti/tools/matrixtools.py
These changes are largely incidental to this PR. What we should really do with this functions is find everywhere they're called and then just in-line their one-line implementations.

2024-03-20 18:38 UTC, rileyjmurray commented on pygsti/algorithms/gaugeopt.py
> +            """
This is just formatting changes.

2025-03-25 14:36 UTC, rileyjmurray commented
**EDIT**: we now have an open issue about handling this sort of thing #633.

-------------------------------
Text from an email Piper sent (not showing plots since they contained real data):
> I was looking at the model violation tab, trying to work out why the smaller L models weren’t fitting the data as well as might be expected as quantified by Nsigma. I think this maybe be a function of how we calculate Nsigma = (2delta logl -k)/sqrt(2k). The number of non-gauge model parameters N_p is reported as 351 in the leakage-enhanced GST report (I don’t have any particular sense of whether this is correct). The number of data points N_s is 193 for L=1. This means that k (the degrees of freedom) is negative if you just calculate it as N_s-N_p. In cases like this, pyGSTi chooses k=1. k remains small until L is fairly large, which means two delta logl must be quite small for Nsigma to be small. This explains why we don’t see any red boxes in the per sequence detail for the L=1 iteration (and Nsigma is large enough that I would expect to see some or at least more dark gray squares than can be seen).  
>
> If you directly compare two delta logl between the two fits, you can see that the two delta logl is in fact smaller in the leakage-enhanced report than in the standard report.

I think the solution here is just to make sure that the first iteration of leakage-aware GST uses L=2 instead of L=1. (Or, more generally, we use the smallest L where N_s > N_p.)

2025-07-24 21:29 UTC, rileyjmurray reviewed
Leaving file-level comments so @coreyostrove and I can figure out what to split out from this PR.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/protocols/gst.py
Changes needed for leakage analysis of the kind I run in existing notebooks.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/factory.py
Changes core to leakage analysis (and which have benefits in other contexts).

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/reportables.py
Changes core to leakage analysis. (Plus error handling of value more broadly.)

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/reportables.py
Need to resolve some "TO WRITE" notes in this file.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/section/gauge.py
Changes core to leakage analysis.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/section/summary.py
Changes core to leakage analysis.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/report/templates/standard_html_report/tabs/GaugeVariants.html
Need to discuss if we want to keep this change; see also pygsti/report/templates/standard_pdf_report.tex.

2025-07-24 21:29 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
Not leakage-specific, but necessary for leakage analysis.

2025-07-24 21:29 UTC, rileyjmurray commented on test/unit/tools/test_optools.py
Modest tests for code used in leakage analysis

2025-07-25 23:35 UTC, rileyjmurray commented on pygsti/modelmembers/povms/tppovm.py
readability

2025-07-25 23:36 UTC, rileyjmurray commented on pygsti/modelmembers/states/densestate.py
Figuring this one out was a doozy. I'm certain that I could make a test which caused the existing code to break without doing anything leakage-specific.

2025-08-01 18:06 UTC, rileyjmurray commented on pygsti/algorithms/gaugeopt.py
> +        # add support back, but I just want to keep things simple. -- Riley
@coreyostrove, the current changes remove support for the 
transform-target Frobenius norm loss when ``_create_objective_fn``(in gaugeopt.py) is passed a value for ``method`` other than ``"ls"``. Does this change sound okay to you? If so, I'll adjust the comment accordingly.

2025-08-01 18:07 UTC, rileyjmurray commented on pygsti/circuits/circuit.py
> +                return self.tup == x.tup
This change is necessary for correctness.

2025-08-01 18:08 UTC, rileyjmurray commented on pygsti/data/dataset.py
> +
TODO: create a test case showing why this is needed, or revert this change.

2025-08-01 18:08 UTC, rileyjmurray commented on pygsti/modelmembers/modelmembergraph.py
> +    def load_modelmembers_from_serialization_dict(sdict, parent_model):
There are no child classes of ModelMemberGraph, so there's no benefit to a classmethod over a staticmethod.

2025-08-01 18:13 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
I collapsed this ``if-else`` branching to always use the ``if`` branch. All I needed to do was to set Ti to None if T is None.

2025-08-01 18:18 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> -        #    gen_dG = u[:, 0:rank]
A change along this lines is needed to satisfy the assertion at the end of this function.  The problematic case is when we hit the ``item_weights is not None`` codepath and the matrix ``metric = _np.diag(metric_diag) `` ends up being singular (for example, because all SPAM weight was zero). 

This would be the first change to this function since it was introduced in [this commit](https://github.com/sandialabs/pyGSTi/commit/159efbf6b19579ac9be618839bea99f8913dc044#diff-2cde56589c9c701a958943ff86c4f7d5c7d2c8d6b8eba42ee081b6d535a22b9f).

This function is called twice in this file. One call is a diagnostic/testing function that was only written for development purposes. The other call is in ExplicitOpModelCalc.nongauge_projector. If you look at how the output of this function is used in that function, you'll see that there's no harm in this function returning orthonormal bases for the two subspaces. In fact, ExplicitOpModelCalc.nongauge_projector is just doing extra work given an assumption of orthonormality. I'd prefer to _not_ change that function in this PR because we can take care of that in the audit for np.linalg.inv (see #454).

This function is also called six times in confidenceregionfactory.py. Some of those calls provide values for item_weights or non_gauge_mix_mx. As far as I understand, there's no harm in us returning orthonormal bases from this function in those contexts.

2025-08-01 18:21 UTC, rileyjmurray commented on pygsti/report/reportables.py
> +                   "TO-WRITE"),
Write me.

2025-08-01 18:21 UTC, rileyjmurray commented on pygsti/report/reportables.py
> +                    "TO WRITE"),
Write me.

2025-08-01 18:30 UTC, rileyjmurray commented on pygsti/report/templates/standard_html_report/tabs/GaugeVariants.html
> +	{{ final_gates_vs_target_table_gauge_var|render }}
Typesetting.

2025-08-01 18:30 UTC, rileyjmurray commented on pygsti/report/templates/standard_pdf_report.tex
> +    \caption{\textbf{Individual gate error metrics} This table presents various (gauge-variant) metrics that quantify errors in each individual estimated logic gate, with respect to the ideal target
Typesetting.

2025-08-05 22:04 UTC, nkoskelo commented on pygsti/baseobjs/basis.py
>          # Note: this assertion also means dim == product(component_elsizes) == elsize, so basis is *simple*
There are some misspellings within the file which would be nice to correct.
-"natrual" is misspelled on line 1601 and line 75.
- "woudl" is misspelled on line 1742.
- "interpeted" is misspelled on line 78.

2025-08-05 22:09 UTC, nkoskelo commented on pygsti/baseobjs/basisconstructors.py
> +    return ("I", "X", "Y", "Z", "LX0", "LX1", "LY0", "LY1", "L")
I assume that, "I", "X", "Y", and "Z" should be the standard leakage free Clifford gates and that "LXt" is a leakage X gate where the data leaks into the "t" component of the Bloch sphere. Or is this a leakage into another qubit? A comment clarifying this in the code would be useful.

2025-08-05 22:22 UTC, nkoskelo commented on pygsti/circuits/circuit.py
>          if isinstance(x, Circuit):
Since you are changing this file anyway, there are some misspellings which could be corrected.
- We have numerous cases were we raise an error with ("Error intializing Circuit: ")
- "arbirary" on line 897.
- "suject" on line 3548.
- "diration" on line 3844.
- "whcih" on line 4120.
- "repetative" on line 4627.

2025-08-05 22:30 UTC, nkoskelo commented on pygsti/data/dataset.py
> +            for layer in circuit.layertup:
Instead of needing to repeat the same logic of iterating over the layers of a circuit to find the distinct label names, why not have a function within circuit or circuit tools which converts a circuit to a set of gate names used? Perhaps we could also have a function which maps a circuit to a dictionary of gate names whose values are the number of times that specific gate appears within the circuit?

2025-08-05 22:34 UTC, nkoskelo commented on pygsti/extras/idletomography/idtcore.py
> -            assert(mx.shape == (4, 4))
This could also be added by using ``assert (item_to_check), msg_on_failure``. This way when you optimize the python code with python -o the assert statement will be removed. Currently, the if block may still exist after the optimization pass. If you specifically want this to be a ValueError and not an AssertionError then please ignore this.

2025-08-05 22:38 UTC, nkoskelo commented on pygsti/extras/idletomography/idtcore.py
>          # StaticArbitraryOp, LindbladDenseOp, other gates...
We also have some spelling errors that could be fixed in this file.
- "conventient" on line 34.
- "corresponging" on line 161 and 240.
- "repectively" on lines 323, 702, and 787.

2025-08-05 22:42 UTC, nkoskelo commented on pygsti/modelmembers/modelmembergraph.py
>      """A directed acyclic graph of dependencies of ModelMembers"""
Misspelling on line 176 for "derefernced".

2025-08-05 22:49 UTC, nkoskelo commented on pygsti/modelmembers/operations/linearop.py
Misspellings:
- "transfomed" on lines 398, 429.
- "accomodate" on line 30.

2025-08-05 23:13 UTC, nkoskelo commented on pygsti/modelmembers/operations/linearop.py
> +    @property
Should we add warnings to suggest that people use the ```shape``` parameter as opposed to relying on ```._rep.shape```?

2025-08-05 23:15 UTC, nkoskelo commented on pygsti/modelmembers/operations/linearop.py
> +    def shape(self):
A type signature for this function would be nice.

2025-08-05 23:36 UTC, nkoskelo commented on pygsti/modelmembers/povms/tppovm.py
Some type signatures for the functions would improve the readability of the code.

2025-08-05 23:42 UTC, nkoskelo commented on pygsti/modelmembers/states/densestate.py
> +        try:
Please add a regression test which can trigger this code path.

2025-08-05 23:45 UTC, nkoskelo commented on pygsti/modelmembers/states/densestate.py
Misspellings:
- "mimicing" on line 28.

2025-08-05 23:46 UTC, nkoskelo commented on pygsti/models/explicitcalc.py
> +import scipy.linalg as _la
Maybe import as ```_sla``` instead of ```_la```. It can be common practice as well to ```import numpy.linalg as la``` which may result in confusion in the future.

2025-08-05 23:52 UTC, nkoskelo commented on pygsti/models/explicitcalc.py
Misspellings:
- "prefereable" on line 807.
- "psuedo" on line 800.
- "substitue" on line 796.
- "tranformations" on line 752.
- "whic" on line 715.
- "multipy" on line 594.
- "coefficents" on line 594.
- "bookeeping" on line 536.
- "subtituted"  on line 135.
- "dimenstion" on line 69 and 45.
- "abount" on line 36.

2025-08-05 23:55 UTC, nkoskelo commented on pygsti/models/explicitcalc.py
> +                val = _np.linalg.norm(delta.flatten())
The Frobenius norm on the 2D array delta would return the same. So we do not need to explicitly call ```flatten()```.

2025-08-06 00:00 UTC, nkoskelo commented on pygsti/models/explicitcalc.py
> +        Ti = None if T is None else _np.linalg.pinv(T)
Do we know any information about T? Or are we trying to keep this for general matrices?

2025-08-06 00:02 UTC, nkoskelo commented on pygsti/models/explicitcalc.py
> +        r = _np.count_nonzero(s >= TOL*s[0])
Can we label this as numerical rank instead of ```r``` so that we have a search term in the future?

2025-08-06 00:07 UTC, nkoskelo commented on pygsti/tools/jamiolkowski.py
>      standard (matrix unit) basis, but does so more quickly than
Do we have a test that proves that this routine is better than ```jamiolkowski_iso``` in the case of standard (matrix unit) basis? It would be nice to link the test / paper / theorem here.

2025-08-06 00:10 UTC, nkoskelo commented on pygsti/tools/jamiolkowski.py
Misspellings:
- "particuarly" on line 224.
- "arbitarily" on line 345, and 376.
- "matricies" on line 405.

2025-08-06 00:12 UTC, nkoskelo commented on pygsti/tools/jamiolkowski.py
We are not using the ```from pygsti.tools import matrixtools as _mt```. Therefore, we should remove the import.

2025-08-06 00:14 UTC, nkoskelo commented on pygsti/tools/jamiolkowski.py
For the function signatures that you modified please add typing information.

2025-08-06 00:16 UTC, nkoskelo commented on pygsti/tools/optools.py
> +from pygsti.baseobjs.basis import Basis as _Basis, DirectSumBasis as _DirectSumBasis, \
I believe you can import these on separate lines if you use ```(``` and ```)``` around the imports. It should also still respect the ```as``` keyword.

2025-08-06 00:18 UTC, nkoskelo commented on pygsti/tools/optools.py
> +def tensorized_with_eye(op, basis, ten_basis=None, std_basis=None, ten_std_basis=None):
Needs a docstring and typing information.

2025-08-06 00:20 UTC, nkoskelo commented on pygsti/tools/optools.py
> +    return 1 - entanglement_fidelity(a, b, mx_basis, is_tp, is_unitary)
To maintain backwards compatibility in the event that ```entanglement_fidelity``` does not return a float, use ```1.0 - entanglement_fidelity```.

2025-08-06 00:23 UTC, nkoskelo commented on pygsti/tools/optools.py
Misspellings:
- "paramterization" on line 2660.
- "coeffiecients" on line 2162.
- "requrested" on line 2316.
- "matricies" on line 1845.
- "multply" on line 1831.
- "fromt" on line 1713 (looks like should be "from the")
- "funtion" on line 1054.
- "Decompse" on line 1052.

2025-08-06 00:26 UTC, nkoskelo commented on pygsti/tools/sdptools.py
> +    # Maximize 1/2 ( < J, X > + < J.dag, X.dag > )
I assume J.dag is the diagonal of J.

2025-08-06 00:30 UTC, nkoskelo commented on pygsti/tools/sdptools.py
There are unused imports in this file.

2025-08-06 00:31 UTC, nkoskelo commented on pygsti/tools/sdptools.py
Since this is a new file, it would also be nice to have a type signature for each of the functions.

2025-08-06 19:57 UTC, rileyjmurray commented on pygsti/baseobjs/basis.py
>          # Note: this assertion also means dim == product(component_elsizes) == elsize, so basis is *simple*
I'll defer spelling fixes until we resolve all other comments. (I'll only leave a comment to that effect here.)

2025-08-06 20:17 UTC, rileyjmurray commented on pygsti/baseobjs/basisconstructors.py
> +    return ("I", "X", "Y", "Z", "LX0", "LX1", "LY0", "LY1", "L")
Done

2025-08-06 20:22 UTC, rileyjmurray commented on pygsti/extras/idletomography/idtcore.py
> -            assert(mx.shape == (4, 4))
I didn't know about the -o flag in Python! Very cool.

That said, in this case I definitely want a value error.

2025-08-06 20:25 UTC, rileyjmurray commented on pygsti/modelmembers/operations/linearop.py
> +    @property
I like that idea, but it's hard to implement. There may well be contexts in which someone's working just with a rep and not a LinearOperator. In those cases it's fine to access ``rep.shape``. 

We _can_ CTRL+F for ``._rep.shape``, though.

2025-08-06 20:28 UTC, rileyjmurray commented on pygsti/modelmembers/operations/linearop.py
> +    @property
Looks like the only hit for ``._rep.shape`` is in this file. So I'll mark this as resolved.

2025-08-06 20:28 UTC, rileyjmurray commented on pygsti/modelmembers/operations/linearop.py
> +    def shape(self):
Excellent catch

2025-08-06 20:32 UTC, rileyjmurray commented on pygsti/modelmembers/povms/tppovm.py
I agree. Since my changes to this file were only for readability in the first place, it's fair that I should be more comprehensive.

2025-08-06 20:43 UTC, rileyjmurray commented on pygsti/modelmembers/povms/tppovm.py
Uhh... actually, I'm going to punt on this. All the complexity of the types is inherited from basepovm.py.

In the spirit of my original agreement I _will_ roll-back the readability change. It was extremely minor anyway.

2025-08-06 20:45 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> +import scipy.linalg as _la
Looks like we only use numpy.linalg as nla.
<img width="336" height="417" alt="image" src="https://github.com/user-attachments/assets/67908154-0b05-42a6-96ef-db13c39309c6" />

So I'll keep it as _la here.

2025-08-06 20:46 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> +                val = _np.linalg.norm(delta.flatten())
Fair!

2025-08-06 20:58 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> -        #    gen_dG = u[:, 0:rank]
Turns out there is harm in always returning orthonormal bases, at least for the function calls in confidenceregionfactory.py. The issue is that for a function $x\mapsto f(x)$ with Hessian $H(x)$, the Hessian of the function $x\mapsto f(A^{-1} x)$ is $A^T H(x) A$. If $A$ is non-orthogonal then $A^T H(x) A$ will differ from $H(x)$ by more then just a unitary transformation (obvious check: take the determinant of both matrices).

I'll revert this functional change and just leave comments for the future person who finds themselves with unhandled exceptions here.

2025-08-06 21:08 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> -        #    gen_dG = u[:, 0:rank]
UGGGGHHH but nullspace_qr was already only returning an orthonormal basis. 

I hate this. I guess I'll keep my change after all.

While I'm on this subject, I'm happy to change r to numerical_rank. I'll also remove the assert statement at the end of this function. Calling svd with full_matrices=True ensures that u is square, so the assertion was trivially satisfied by construction.

2025-08-06 21:09 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> +        Ti = None if T is None else _np.linalg.pinv(T)
Keeping it for general matrices. So there's no special structure to exploit in the pinv calculation.

2025-08-06 21:10 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> +        r = _np.count_nonzero(s >= TOL*s[0])
Done.

2025-08-06 21:17 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
>      standard (matrix unit) basis, but does so more quickly than
I looked into the function calls that this implementation triggers. It seems this performs all calculations as memory movement plus two big calls to GEMM. Compare to the "not fast" implementation, which needs a ton of explicit Kronecker products and AXPYs. So I don't think we need tests showing this function is faster than the "not fast" one.

2025-08-06 21:17 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
Done.

2025-08-06 21:18 UTC, rileyjmurray commented on pygsti/tools/optools.py
> +from pygsti.baseobjs.basis import Basis as _Basis, DirectSumBasis as _DirectSumBasis, \
Done!

2025-08-06 21:21 UTC, rileyjmurray commented on pygsti/tools/optools.py
> +    return 1 - entanglement_fidelity(a, b, mx_basis, is_tp, is_unitary)
I'm fairly confident that the float coercion was in case entanglement_fidelity returned a complex number. Looking at entanglement_fidelity (and then fidelity) shows that we'll always get real numbers, so I'll keep this change as-is.

2025-08-06 21:22 UTC, rileyjmurray commented on pygsti/tools/sdptools.py
> +    # Maximize 1/2 ( < J, X > + < J.dag, X.dag > )
This is just comment for us humans. Will switch to dagger.

2025-08-06 21:53 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
Done.

2025-08-06 22:12 UTC, rileyjmurray commented on pygsti/tools/optools.py
> +def tensorized_with_eye(op, basis, ten_basis=None, std_basis=None, ten_std_basis=None):
Done.

2025-08-06 22:22 UTC, rileyjmurray commented on pygsti/tools/sdptools.py
Done.

2025-08-07 01:34 UTC, coreyostrove commented
> Text from an email Piper sent (not showing plots since they contained real data):
> 
> > I was looking at the model violation tab, trying to work out why the smaller L models weren’t fitting the data as well as might be expected as quantified by Nsigma. I think this maybe be a function of how we calculate Nsigma = (2delta logl -k)/sqrt(2k). The number of non-gauge model parameters N_p is reported as 351 in the leakage-enhanced GST report (I don’t have any particular sense of whether this is correct). The number of data points N_s is 193 for L=1. This means that k (the degrees of freedom) is negative if you just calculate it as N_s-N_p. In cases like this, pyGSTi chooses k=1. k remains small until L is fairly large, which means two delta logl must be quite small for Nsigma to be small. This explains why we don’t see any red boxes in the per sequence detail for the L=1 iteration (and Nsigma is large enough that I would expect to see some or at least more dark gray squares than can be seen).
> > If you directly compare two delta logl between the two fits, you can see that the two delta logl is in fact smaller in the leakage-enhanced report than in the standard report.
> 
> I think the solution here is just to make sure that the first iteration of leakage-aware GST uses L=2 instead of L=1. (Or, more generally, we use the smallest L where N_s > N_p.)

This isn’t a uniquely leakage-related shortcoming, I’ve encountered this in other settings too (with really aggressive FPR schemes when not forcing inclusion of LGST circuits, for example) and I suggest we open up a separate github issue for this and give some additional thought to how we should be approaching the statistics in this case.

2025-08-07 01:36 UTC, coreyostrove commented on pygsti/algorithms/gaugeopt.py
> +        # add support back, but I just want to keep things simple. -- Riley
I don’t even know what these do, and have never used them, so I think removing them is fine.

2025-08-08 04:11 UTC, coreyostrove requested changes
Just finished my first pass through. This is a ton of effort and these contributions are sincerely appreciated. Thank you as always for the excellent work, @rileyjmurray!

Of the comments I've left, the only one I am deeply concerned about is the potential bug that I've pointed out in the cost function for gauge optimization as it pertains to instruments. I have good reason to suspect (I mean, the git history is pretty clear and this present on develop so it isn't really a suspicion) that in the event there is a bug here it is very likely you had nothing to do with introducing it, but since you're already knee deep in this code I'd ask that you take a look and if necessary clean this up on our behalf.

Rest of my comments are either minor clarifying questions or otherwise nice-to-have but non-blocking requests. I've also added my concurrence with a couple comments/suggestions from @nkoskelo.

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/algorithms/gaugeopt.py
> +                raise ValueError()
Please add a descriptive error message for this case.

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/algorithms/gaugeopt.py
> +        # add support back, but I just want to keep things simple. -- Riley
Please add an error message for the AssertionError indicating that these metrics are not supported when doing leakage-aware gauge optimization (i.e. n_leak>0).

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/algorithms/gaugeopt.py
> +                """
I think there might be a (likely preexisting) bug here related to instruments. For the fidelity and tracedistance metrics I’m not seeing the instrument elements being accessed (except in passing in the spam metric computation where it is just used to filter the item weights). For frobenius this is harder to see, but I took a look at the implementation of the ‘frobeniusdist’ method for ExplicitOpModels [here](https://github.com/sandialabs/pyGSTi/blob/822148ab0f2712aa7fb0c680ebc9fa048ad76fb0/pygsti/models/explicitcalc.py#L109) and I’m not seeing instruments there either.

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/circuits/circuit.py
> +                return self.tup == x.tup
These look functionally equivalent to me. I’ll take your word for it, but for my own edification what about the original version was incorrect?

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/data/dataset.py
> +            for layer in circuit.layertup:
This is a good suggestion and I think it would be an independently useful primitive for circuits to return their unique gate labels, probably with some flags to control matching behavior (e.g. just label names versus full labels with sslbls).

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/models/explicitcalc.py
> +            # we're in the special case that I'm creating.
What is the special case?

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/protocols/confidenceregionfactory.py
> +        hessian /= 2
This is just using the following factoid about quadratic forms, right? https://en.wikipedia.org/wiki/Quadratic_form#General_case

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/report/reportables.py
It looks like most/all of these reportable functions hard code in that n_leak is one. I don't think there is anything to flag a user specifying something different in `construct_standard_report`, though. That is fine for now, but maybe add an assertion for this to avoid unexpected behavior? (i.e. a user being confused by why this was quietly changed under the hood).

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/tools/leakage.py
A general comment, a lot of these new functions lack doctrings explaining how/what they do. Some of these also look like they might not be user facing with their API. So please add docstrings where you can for functions that you expect to be user-facing, and mark others as part of the internal API (e.g. with a leading underscore).

2025-08-08 04:11 UTC, coreyostrove commented on pygsti/tools/sdptools.py
Similar comment to the one I left on the leakage model regarding docstrings and API-level.

2025-08-08 14:42 UTC, rileyjmurray commented on pygsti/report/reportables.py
Good point. I'll update the construct_standard_report docstring and raise an exception if the user passes in n_leak other than 0 or 1.

2025-08-08 14:45 UTC, rileyjmurray commented on pygsti/tools/leakage.py
You got me! Will do so.

2025-08-08 19:40 UTC, rileyjmurray commented on pygsti/algorithms/gaugeopt.py
> +                raise ValueError()
Done!

2025-08-08 19:41 UTC, rileyjmurray commented on pygsti/models/explicitcalc.py
> +            # we're in the special case that I'm creating.
Good catch. That's a terrible comment for me to have left in place.

Rather than answer your question, I've refactored this function in order to remove the distinction between the two cases.

2025-08-08 22:39 UTC, rileyjmurray commented on pygsti/tools/leakage.py
> +    return tm_3level
Needs docstring.

2025-08-08 22:45 UTC, rileyjmurray commented on pygsti/tools/leakage.py
> +    return
Need documentation.

2025-08-19 07:02 UTC, rileyjmurray commented on pygsti/tools/sdptools.py
I'm going to say that everything here is in the private API for now.

2025-08-19 07:06 UTC, rileyjmurray commented
@coreyostrove I think I've addressed your comments. Just pushed what should be the last round of changes.

2025-08-19 14:36 UTC, coreyostrove commented
> @coreyostrove I think I've addressed your comments. Just pushed what should be the last round of changes.

I think the only major outstanding concern here is the bug I alluded to with gauge optimization for instruments. Since this is a pre-existing bug I am alright with tabling this for the purposes of this PR, but we should open up a new github issue to track it. If you have time today can you open this issue? If not I can do so myself later this evening.

2025-08-19 15:02 UTC, coreyostrove approved these changes
Fantastic work, @rileyjmurray! Thank you for the significant effort this work represents and your contributions advancing our leakage modeling capabilities. Merge at will.

One last request as you merge things in, can you flesh out the summary in the PR? That’d be helpful as I prepare release notes (and for posterity).

2025-08-19 22:44 UTC, rileyjmurray commented on pygsti/protocols/confidenceregionfactory.py
> +        hessian /= 2
Essentially, yes. But if your function is twice continuously differentiable you're guaranteed that the Hessian is symmetric. This symmetrization is to eliminate issues from rounding errors in finite-difference methods.

2025-08-20 02:42 UTC, rileyjmurray commented
The single failing test is caused by implementation details of /test/unit/mpi/test_mpi.py::MPITester::test_all. Merging as-is.

2025-08-20 02:42 UTC, merged